version: "3.9"

services:

  api-gateway:
    build: ./api_gateway
    ports:
      - "10000:10000"
    depends_on:
      - employee-service
      - schedule-service
      - student-service
      - student-group-service
      - curriculum-service
    env_file:
      - ./api_gateway/.env.docker
    environment:
    - DOCKER_ENV=true

  employee-service:
    build: ./services/employee
    expose:
      - "10001"
    env_file:
      - ./services/employee/.env.docker
    environment:
    - DOCKER_ENV=true
  
  schedule-service:
    build: ./services/schedule
    expose:
      - "10002"
    depends_on:
      - employee-service
      - student-group-service
      - student-service
    env_file:
      - ./services/schedule/.env.docker
    environment:
    - DOCKER_ENV=true

  student-service:
    build: ./services/student
    expose:
      - "10003"
    env_file:
      - ./services/student/.env.docker
    environment:
    - DOCKER_ENV=true
  
  student-group-service:
    build: ./services/student_group
    expose:
      - "10004"
    depends_on:
      - student-service
    env_file:
      - ./services/student_group/.env.docker
    environment:
    - DOCKER_ENV=true
  
  curriculum-service:
    build: ./services/curriculum
    expose:
      - "10005"
    env_file:
      - ./services/curriculum/.env.docker
    environment:
    - DOCKER_ENV=true
  