import { LuUser, LuBookCopy, LuGraduationCap, LuUsers, LuNotebookText, LuUniversity, LuSheet } from 'react-icons/lu'
import type { ServiceDef } from '../types/admin'

export const SERVICES: ServiceDef[] = [
  // ── EMPLOYEE ──────────────────────────────────────────────────────────────
  {
    key: 'employee',
    label: 'Employee Service',
    icon: <LuUser />,
    baseURL: '/api/employee',
    tables: [
      {
        key: 'employees',
        label: 'Employees',
        listEndpoint: '/employees',
        itemEndpoint: '/employee',
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'first_name', label: 'First Name' },
          { key: 'last_name', label: 'Last Name' },
          { key: 'middle_name', label: 'Middle Name' },
          { key: 'phone_number', label: 'Phone' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
          { key: 'deleted_at', label: 'Deleted At' },
        ],
        fields: [
          { key: 'first_name', label: 'First Name', required: true },
          { key: 'last_name', label: 'Last Name', required: true },
          { key: 'middle_name', label: 'Middle Name' },
          { key: 'phone_number', label: 'Phone Number' },
        ],
      },
      {
        key: 'teachers',
        label: 'Teachers',
        listEndpoint: '/teachers',
        itemEndpoint: '/teacher',
        columns: [
          { key: 'employee_id', label: 'Employee ID' },
          { key: 'email', label: 'Email' },
          { key: 'academic_rank_id', label: 'Academic Rank ID' },
          { key: 'academic_degree_id', label: 'Academic Degree ID' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
          { key: 'deleted_at', label: 'Deleted At' },
        ],
        fields: [
          {
            key: 'employee_id', label: 'Employee', required: true,
            relation: { serviceKey: 'employee', tableKey: 'employees', labelKey: 'last_name' },
          },
          { key: 'email', label: 'Email', required: true },
          {
            key: 'academic_rank_id', label: 'Academic Rank', required: true,
            relation: { serviceKey: 'employee', tableKey: 'academic-ranks', labelKey: 'title' },
          },
          {
            key: 'academic_degree_id', label: 'Academic Degree',
            relation: { serviceKey: 'employee', tableKey: 'academic-degrees', labelKey: 'title' },
          },
        ],
      },
      {
        key: 'academic-ranks',
        label: 'Academic Ranks',
        listEndpoint: '/academic-ranks',
        itemEndpoint: '/academic-rank',
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'title', label: 'Title' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [{ key: 'title', label: 'Title', required: true }],
      },
      {
        key: 'academic-degrees',
        label: 'Academic Degrees',
        listEndpoint: '/academic-degrees',
        itemEndpoint: '/academic-degree',
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'title', label: 'Title' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [{ key: 'title', label: 'Title', required: true }],
      },
    ],
  },

  // ── CURRICULUM ────────────────────────────────────────────────────────────
  {
    key: 'curriculum',
    label: 'Curriculum Service',
    icon: <LuBookCopy />,
    baseURL: '/api/curriculum',
    tables: [
      {
        key: 'curriculums',
        label: 'Curriculums',
        listEndpoint: '/curriculums',
        itemEndpoint: '/curriculum',
        numericKeys: ['duration_years'],
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'name', label: 'Name' },
          { key: 'duration_years', label: 'Duration (years)' },
          { key: 'effective_from', label: 'Effective From' },
          { key: 'effective_to', label: 'Effective To' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [
          { key: 'name', label: 'Name', required: true },
          { key: 'duration_years', label: 'Duration (years)', required: true },
          { key: 'effective_from', label: 'Effective From (YYYY-MM-DD)', required: true },
          { key: 'effective_to', label: 'Effective To (YYYY-MM-DD)' },
        ],
      },
      {
        key: 'semesters',
        label: 'Semesters',
        listEndpoint: '/semesters',
        itemEndpoint: '/semester',
        numericKeys: ['number'],
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'curriculum_id', label: 'Curriculum ID' },
          { key: 'number', label: 'Number' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [
          {
            key: 'curriculum_id', label: 'Curriculum', required: true,
            relation: { serviceKey: 'curriculum', tableKey: 'curriculums', labelKey: 'name' },
          },
          { key: 'number', label: 'Semester Number', required: true },
        ],
      },
      {
        key: 'disciplines',
        label: 'Disciplines',
        listEndpoint: '/disciplines',
        itemEndpoint: '/discipline',
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'name', label: 'Name' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [{ key: 'name', label: 'Name', required: true }],
      },
      {
        key: 'lesson-types',
        label: 'Lesson Types',
        listEndpoint: '/lesson-types',
        itemEndpoint: '/lesson-type',
        numericKeys: ['hours_value'],
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'name', label: 'Name' },
          { key: 'hours_value', label: 'Hours per lesson' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [
          { key: 'name', label: 'Name', required: true },
          { key: 'hours_value', label: 'Hours per lesson', required: true },
        ],
      },
      {
        key: 'semester-disciplines',
        label: 'Semester Disciplines',
        listEndpoint: '/semester-disciplines',
        itemEndpoint: '/semester-discipline',
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'semester_id', label: 'Semester ID' },
          { key: 'discipline_id', label: 'Discipline ID' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [
          {
            key: 'semester_id', label: 'Semester', required: true,
            relation: { serviceKey: 'curriculum', tableKey: 'semesters', labelKey: 'number' },
          },
          {
            key: 'discipline_id', label: 'Discipline', required: true,
            relation: { serviceKey: 'curriculum', tableKey: 'disciplines', labelKey: 'name' },
          },
        ],
      },
      {
        key: 'lesson-type-assignments',
        label: 'Lesson Type Assignments',
        listEndpoint: '/lesson-type-assignments',
        itemEndpoint: '/lesson-type-assignment',
        numericKeys: ['required_hours'],
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'lesson_type_id', label: 'Lesson Type ID' },
          { key: 'discipline_id', label: 'Discipline ID' },
          { key: 'required_hours', label: 'Required Hours' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [
          {
            key: 'lesson_type_id', label: 'Lesson Type', required: true,
            relation: { serviceKey: 'curriculum', tableKey: 'lesson-types', labelKey: 'name' },
          },
          {
            key: 'discipline_id', label: 'Discipline', required: true,
            relation: { serviceKey: 'curriculum', tableKey: 'disciplines', labelKey: 'name' },
          },
          { key: 'required_hours', label: 'Required Hours', required: true },
        ],
      },
    ],
  },

  // ── STUDENT ───────────────────────────────────────────────────────────────
  {
    key: 'student',
    label: 'Student Service',
    icon: <LuGraduationCap />,
    baseURL: '/api/student',
    tables: [
      {
        key: 'students',
        label: 'Students',
        listEndpoint: '/students',
        itemEndpoint: '/student',
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'first_name', label: 'First Name' },
          { key: 'last_name', label: 'Last Name' },
          { key: 'middle_name', label: 'Middle Name' },
          { key: 'email', label: 'Email' },
          { key: 'phone_number', label: 'Phone' },
          { key: 'semester_id', label: 'Semester ID' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
          { key: 'deleted_at', label: 'Deleted At' },
        ],
        fields: [
          { key: 'first_name', label: 'First Name', required: true },
          { key: 'last_name', label: 'Last Name', required: true },
          { key: 'email', label: 'Email', required: true },
          {
            key: 'semester_id', label: 'Semester', required: true,
            relation: { serviceKey: 'curriculum', tableKey: 'semesters', labelKey: 'number' },
          },
          { key: 'middle_name', label: 'Middle Name' },
          { key: 'phone_number', label: 'Phone Number' },
        ],
      },
      {
        key: 'semesters',
        label: 'Semesters (read)',
        listEndpoint: '/semesters',
        itemEndpoint: '/semester',
        readOnly: true,
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'curriculum_id', label: 'Curriculum ID' },
          { key: 'number', label: 'Number' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
      },
    ],
  },

  // ── STUDENT GROUP ─────────────────────────────────────────────────────────
  {
    key: 'student-group',
    label: 'Student Group Service',
    icon: <LuUsers />,
    baseURL: '/api/student-group',
    tables: [
      {
        key: 'group-cohorts',
        label: 'Group Cohorts',
        listEndpoint: '/group-cohorts',
        itemEndpoint: '/group-cohort',
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'name', label: 'Name' },
          { key: 'semester_id', label: 'Semester ID' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [
          { key: 'name', label: 'Name', required: true },
          {
            key: 'semester_id', label: 'Semester', required: true,
            relation: { serviceKey: 'student-group', tableKey: 'semesters', labelKey: 'number' },
          },
        ],
      },
      {
        key: 'student-groups',
        label: 'Student Groups',
        listEndpoint: '/student-groups',
        itemEndpoint: '/student-group',
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'name', label: 'Name' },
          { key: 'group_cohort_id', label: 'Group Cohort ID' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [
          { key: 'name', label: 'Name', required: true },
          {
            key: 'group_cohort_id', label: 'Group Cohort', required: true,
            relation: { serviceKey: 'student-group', tableKey: 'group-cohorts', labelKey: 'name' },
          },
        ],
      },
      {
        key: 'group-members',
        label: 'Group Members',
        listEndpoint: '/group-members',
        itemEndpoint: '/group-member',
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'studentId', label: 'Student ID' },
          { key: 'group_cohort_id', label: 'Group Cohort ID' },
          { key: 'student_group_id', label: 'Student Group ID' },
          { key: 'createdAt', label: 'Created At' },
          { key: 'updatedAt', label: 'Updated At' },
        ],
        fields: [
          {
            key: 'studentId', label: 'Student', required: true,
            relation: { serviceKey: 'student-group', tableKey: 'students', labelKey: 'name' },
          },
          {
            key: 'student_group_id', label: 'Student Group', required: true,
            relation: { serviceKey: 'student-group', tableKey: 'student-groups', labelKey: 'name' },
          },
        ],
      },
      {
        key: 'group-cohort-assignments',
        label: 'Cohort Assignments',
        listEndpoint: '/group-cohort-assignments',
        itemEndpoint: '/group-cohort-assignment',
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'group_cohort_id', label: 'Group Cohort ID' },
          { key: 'discipline_id', label: 'Discipline ID' },
          { key: 'lesson_type_id', label: 'Lesson Type ID' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [
          {
            key: 'group_cohort_id', label: 'Group Cohort', required: true,
            relation: { serviceKey: 'student-group', tableKey: 'group-cohorts', labelKey: 'name' },
          },
          {
            key: 'discipline_id', label: 'Discipline', required: true,
            relation: { serviceKey: 'student-group', tableKey: 'disciplines', labelKey: 'name' },
          },
          {
            key: 'lesson_type_id', label: 'Lesson Type', required: true,
            relation: { serviceKey: 'student-group', tableKey: 'lesson-types', labelKey: 'name' },
          },
        ],
      },
      {
        key: 'semesters',
        label: 'Semesters (read)',
        listEndpoint: '/semesters',
        itemEndpoint: '/semester',
        readOnly: true,
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'curriculum_id', label: 'Curriculum ID' },
          { key: 'number', label: 'Number' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
      },
      {
        key: 'students',
        label: 'Students (read)',
        listEndpoint: '/students',
        itemEndpoint: '/student',
        readOnly: true,
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'name', label: 'Name' },
          { key: 'semester_id', label: 'Semester ID' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
      },
      {
        key: 'disciplines',
        label: 'Disciplines (read)',
        listEndpoint: '/disciplines',
        itemEndpoint: '/discipline',
        readOnly: true,
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'name', label: 'Name' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
      },
      {
        key: 'lesson-types',
        label: 'Lesson Types (read)',
        listEndpoint: '/lesson-types',
        itemEndpoint: '/lesson-type',
        readOnly: true,
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'name', label: 'Name' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
      },
    ],
  },

  // ── TEACHER LOAD ──────────────────────────────────────────────────────────
  {
    key: 'teacher-load',
    label: 'Teacher Load Service',
    icon: <LuNotebookText />,
    baseURL: '/api/teacher-load',
    tables: [
      {
        key: 'teacher-loads',
        label: 'Teacher Loads',
        listEndpoint: '/teacher-loads',
        itemEndpoint: '/teacher-load',
        numericKeys: ['group_count'],
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'teacher_id', label: 'Teacher ID' },
          { key: 'discipline_id', label: 'Discipline ID' },
          { key: 'lesson_type_id', label: 'Lesson Type ID' },
          { key: 'group_count', label: 'Group Count' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [
          {
            key: 'teacher_id', label: 'Teacher', required: true,
            relation: { serviceKey: 'teacher-load', tableKey: 'teachers', labelKey: 'name' },
          },
          {
            key: 'discipline_id', label: 'Discipline', required: true,
            relation: { serviceKey: 'teacher-load', tableKey: 'disciplines', labelKey: 'name' },
          },
          {
            key: 'lesson_type_id', label: 'Lesson Type', required: true,
            relation: { serviceKey: 'teacher-load', tableKey: 'lesson-types', labelKey: 'name' },
          },
          { key: 'group_count', label: 'Group Count', required: true },
        ],
      },
      {
        key: 'teachers',
        label: 'Teachers (read)',
        listEndpoint: '/teachers',
        itemEndpoint: '/teacher',
        readOnly: true,
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'name', label: 'Name' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
      },
      {
        key: 'disciplines',
        label: 'Disciplines (read)',
        listEndpoint: '/disciplines',
        itemEndpoint: '/discipline',
        readOnly: true,
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'name', label: 'Name' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
      },
      {
        key: 'lesson-types',
        label: 'Lesson Types (read)',
        listEndpoint: '/lesson-types',
        itemEndpoint: '/lesson-type',
        readOnly: true,
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'name', label: 'Name' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
      },
    ],
  },

  // ── ASSET ─────────────────────────────────────────────────────────────────
  {
    key: 'asset',
    label: 'Asset Service',
    icon: <LuUniversity />,
    baseURL: '/api/asset',
    tables: [
      {
        key: 'classrooms',
        label: 'Classrooms',
        listEndpoint: '/classrooms',
        itemEndpoint: '/classroom',
        numericKeys: ['capacity'],
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'number', label: 'Number' },
          { key: 'capacity', label: 'Capacity' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [
          { key: 'number', label: 'Classroom Number', required: true },
          { key: 'capacity', label: 'Capacity', required: true },
        ],
      },
    ],
  },

  // ── SCHEDULE ──────────────────────────────────────────────────────────────
  {
    key: 'schedule',
    label: 'Schedule Service',
    icon: <LuSheet />,
    baseURL: '/api/schedule',
    tables: [
      {
        key: 'lesson-slots',
        label: 'Lesson Slots',
        listEndpoint: '/lesson-slots',
        itemEndpoint: '/lesson-slot',
        readOnly: true,
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slot', label: 'Slot' },
          { key: 'weekday', label: 'Weekday', format: 'weekday-ua' },
          { key: 'start_time', label: 'Start Time', format: 'time-ns' },
          { key: 'duration', label: 'Duration', format: 'duration-ns' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
      },
      {
        key: 'lesson-occurrences',
        label: 'Lesson Occurrences',
        listEndpoint: '/lesson-occurrences',
        itemEndpoint: '/lesson-occurrence',
        readOnly: true,
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'study_load_id', label: 'Study Load ID' },
          { key: 'teacher_id', label: 'Teacher ID' },
          { key: 'student_group_id', label: 'Student Group ID' },
          { key: 'lesson_slot_id', label: 'Lesson Slot ID' },
          { key: 'classroom_id', label: 'Classroom ID' },
          { key: 'date', label: 'Date' },
          { key: 'status', label: 'Status' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
      },
      {
        key: 'academic-ranks',
        label: 'Academic Ranks',
        listEndpoint: '/academic-ranks',
        itemEndpoint: '/academic-rank',
        readOnly: false,
        numericKeys: ['priority'],
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'title', label: 'Title' },
          { key: 'priority', label: 'Priority' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
        editFields: [
          { key: 'priority', label: 'Priority', required: true },
        ],
      },
      {
        key: 'lesson-types',
        label: 'Lesson Types (read)',
        listEndpoint: '/lesson-types',
        itemEndpoint: '/lesson-type',
        readOnly: true,
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'name', label: 'Name' },
          { key: 'hours_value', label: 'Hours' },
          { key: 'reserved_weeks', label: 'Reserved Weeks' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
      },
      {
        key: 'teachers',
        label: 'Teachers (read)',
        listEndpoint: '/teachers',
        itemEndpoint: '/teacher',
        readOnly: true,
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'name', label: 'Name' },
          { key: 'academic_rank_id', label: 'Academic Rank ID' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
      },
      {
        key: 'classrooms',
        label: 'Classrooms (read)',
        listEndpoint: '/classrooms',
        itemEndpoint: '/classroom',
        readOnly: true,
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'number', label: 'Number' },
          { key: 'capacity', label: 'Capacity' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
      },
      {
        key: 'student-groups',
        label: 'Student Groups (read)',
        listEndpoint: '/student-groups',
        itemEndpoint: '/student-group',
        readOnly: true,
        columns: [
          { key: 'id', label: 'ID' },
          { key: 'slug', label: 'Slug' },
          { key: 'name', label: 'Name' },
          { key: 'created_at', label: 'Created At' },
          { key: 'updated_at', label: 'Updated At' },
        ],
        fields: [],
      },
    ],
  },
]