package entities

import (
	"fmt"
	"slices"

	"github.com/google/uuid"
)

// StudentGroup represents a university student group in a scheduling context.
//
// The model disallows simultaneous classes and day overloads.
type StudentGroup struct {
	BusyGrid                         // Availability grid.
	LoadService                      // Manages and validates assigned study loads.
	LessonTypeBinder                 // Handles lesson type binding logic.
	ID               uuid.UUID       // Unique identifier of the StudentGroup.
	Name             string          // Human-readable identifier of the StudentGroup.
	MaxLessonsPerDay int             // Day load limit.
	connectedGroups  []*StudentGroup // Groups that share students with this group.
	StudentNumber    int             // Number of students.
}

// NewStudentGroup creates a new StudentGroup instance.
//
// It requires student group id, name, max lessons per day (dl), number of students (sn),
// busy grid (bg), lesson type binder (ltb) and load service (lc).
func NewStudentGroup(
	id uuid.UUID, name string, dl int, sn int,
	bg *BusyGrid, ltb LessonTypeBinder, lc LoadService,
) *StudentGroup {
	return &StudentGroup{ID: id,
		Name:             name,
		MaxLessonsPerDay: dl,
		BusyGrid:         *bg,
		LessonTypeBinder: ltb,
		LoadService:      lc,
		StudentNumber:    sn,
	}
}

// NewDefaultStudentGroup creates a new StudentGroup instance with default configuration.
//
// It requires student group id, name, max lessons per day (dl),
// number of students (sn), and busy grid (bg).
func NewDefaultStudentGroup(id uuid.UUID, name string, dl int, sn int, bg *BusyGrid) *StudentGroup {
	return NewStudentGroup(id, name, dl, sn, bg, NewLessonTypeBinder(), NewLoadService())
}

// ==========================================================================================================
// ============================================= ConnectedGroups ============================================
// ==========================================================================================================

// AddConnectedGroup creates a connection between student groups by adding each group to the other's special field.
// Does not create a duplicate connection if the groups are already connected.
func (sg *StudentGroup) AddConnectedGroup(other *StudentGroup) {
	if slices.Contains(sg.connectedGroups, other) {
		return
	}

	other.connectedGroups = append(other.connectedGroups, sg)
	sg.connectedGroups = append(sg.connectedGroups, other)
}

func (sg *StudentGroup) CountConnectedGroupsNumber() int {
	return len(sg.connectedGroups)
}

func (sg *StudentGroup) ConnectedTo(studentGroup *StudentGroup) bool {
	ind := slices.Index(sg.connectedGroups, studentGroup)
	return ind != -1
}

// ==========================================================================================================
// =========================================== BusyGrid OVERRIDES ===========================================
// ==========================================================================================================

// func (sg *StudentGroup) CountSlotsAtDay(day int) (count int) {
// 	if day < 0 || day > 6 {
// 		return
// 	}
//
// 	for week := 0; sg.CheckDay(day+week*7) == nil; week++ {
// 		currentDay := day + week*7
// 		delta := 0
// 		for slot := range sg.Grid[currentDay] {
// 			if !sg.IsBusy(LessonSlot{Day: currentDay, Slot: slot}) {
// 				delta++
// 			}
// 		}
// 		if delta > sg.MaxLessonsPerDay {
// 			delta = sg.MaxLessonsPerDay
// 		}
// 		count += delta
// 	}
// 	return
// }

// GetFreeSlots returns free slots of the selected day (day).
//
// If a day out of the grid returns an empty array.
func (sg *StudentGroup) GetFreeSlots(day int) (slots []float32) {
	if err := sg.CheckDay(day); err != nil {
		return []float32{}
	}

	slots = make([]float32, len(sg.Grid[day]))

	// the group hasn't lesson that day
	if sg.CountLessonsOn(day) == 0 {
		for i := range slots {
			slots[i] = sg.Grid[day][i]
		}
		return
	}

	for i := range sg.Grid[day] {
		// skip first element to perform away algorithm correctly
		if i == 0 {
			continue
		}

		// if there is a lesson at the current slot and the previous slot is free, mark the previous slot as available
		if sg.IsBusy(LessonSlot{Day: day, Slot: i}) {
			if !sg.IsBusy(LessonSlot{Day: day, Slot: i - 1}) {
				slots[i-1] = sg.Grid[day][i-1]
			}
			// if the current slot is busy and the previous slot is free, mark the current slot as available
		} else {
			if sg.IsBusy(LessonSlot{Day: day, Slot: i - 1}) {
				slots[i] = sg.Grid[day][i]
			}
		}
	}
	return
}

// MoveLessonTo uses the MoveLessonTo BusyGrid method to move the lesson. If the lesson can't be moved
// returns the error generated by the LessonCanBeMoved method.
func (sg *StudentGroup) MoveLessonTo(lesson *Lesson, to LessonSlot) error {
	if err := sg.LessonCanBeMoved(lesson, to); err != nil {
		return err
	}

	return sg.BusyGrid.MoveLessonTo(lesson.LessonSlot, to)
}

// LessonCanBeMoved uses the LessonCanBeMoved BusyGrid check on the first order, then additionally
// checks the type of the day.
func (sg *StudentGroup) LessonCanBeMoved(lesson *Lesson, to LessonSlot) error {
	if err := sg.BusyGrid.LessonCanBeMoved(lesson.LessonSlot, to); err != nil {
		return err
	}

	if !sg.IsDayOfType(lesson.Type, to.Day) {
		return fmt.Errorf("%d is not day of the type %s", to.Day, lesson.Type.Name)
	}

	return nil
}

// func (sg *StudentGroup) GetGetAverageSlotCountOnWeekdays() []int {
// 	result := make([]int, 7)
//
// 	for i := range result {
// 		result[i] = sg.GetAverageSlotCountOnWeekday(i)
// 	}
//
// 	return result
// }

func (sg *StudentGroup) GetAverageSlotCountOnWeekday(weekday int) (result int) {
	result = sg.BusyGrid.GetAverageSlotCountOnWeekday(weekday)
	if result > sg.MaxLessonsPerDay {
		return sg.MaxLessonsPerDay
	}

	return
}

func (sg *StudentGroup) GetLessonOverlapping() []LessonSlot {
	return sg.BusyGrid.GetLessonOverlapping(sg.GetAssignedLessons())
}

func (sg *StudentGroup) GetWeekDaysPriority() []float32 {
	res := sg.BusyGrid.GetWeekDaysPriority()
	teachers := sg.GetTeachers()

	for _, teacher := range teachers {
		teacherPr := teacher.GetWeekDaysPriority()
		for i := range len(res) {
			res[i] *= teacherPr[i]
		}
	}

	return res
}

// ==========================================================================================================
// ======================================= LessonTypeBinder OVERRIDES =======================================
// ==========================================================================================================

// GetNextDayOfType finds the next free day of the selected lesson type. Starts with the start day position.
// The method does NOT return days where the student group is already fully loaded.
//
// Returns -1 if the student group doesn't have a free day.
func (sg *StudentGroup) GetNextDayOfType(lType *LessonType, startDay int) int {
	// if len(sg.LessonTypeBinding[lType].Days) == 0 {
	// 	return -1
	// }

	for i := startDay; sg.CheckDay(i) == nil; i++ {
		if sg.IsDayOfType(lType, i) {
			if !sg.CheckDayOverload(i) {
				return i
			}
		}
	}

	return -1
}

// HasLessonsOfType Returns true if the student group has lessons of type (lType).
func (sg *StudentGroup) HasLessonsOfType(lType *LessonType) bool {
	return slices.Contains(sg.GetLessonTypes(), lType)
}

// BindWeek uses the BindWeek method on the first order.
// Then it binds to connected groups, ignoring their errors.
func (sg *StudentGroup) BindWeek(lType *LessonType, week int) error {
	if err := sg.LessonTypeBinder.BindWeek(lType, week); err != nil {
		return err
	}

	for _, group := range sg.connectedGroups {
		group.LessonTypeBinder.BindWeek(lType, week)
	}

	return nil
}

// BindWeekday uses the BindWeekday method on the first order.
// Then it binds to connected groups, ignoring their errors.
func (sg *StudentGroup) BindWeekday(lType *LessonType, day, slots int) error {
	if err := sg.LessonTypeBinder.BindWeekday(lType, day, slots); err != nil {
		return err
	}

	for _, group := range sg.connectedGroups {
		group.LessonTypeBinder.BindWeekday(lType, day, slots)
	}

	return nil
}

func (sg *StudentGroup) UnbindWeekday(lType *LessonType, day, slots int) error {
	if err := sg.LessonTypeBinder.UnbindWeekday(lType, day, slots); err != nil {
		return err
	}

	for _, group := range sg.connectedGroups {
		group.LessonTypeBinder.UnbindWeekday(lType, day, slots)
	}

	return nil
}

// ==========================================================================================================
// ================================================= OTHERS =================================================
// ==========================================================================================================

// CheckDayOverload returns false if the student group has fewer lessons than the limit, set as MaxLessonsPerDay.
// It uses the CountLessonsOn method to get the number of lessons.
func (sg *StudentGroup) CheckDayOverload(day int) bool {
	if err := sg.CheckDay(day); err != nil {
		return true
	}

	return sg.CountLessonsOn(day) >= sg.MaxLessonsPerDay
}

// AddLesson registers the lesson at all dependent services.
//
// Returns an error if CheckLesson fails.
func (sg *StudentGroup) AddLesson(lesson *Lesson) error {
	err := sg.CheckLesson(lesson)
	if err != nil {
		return err
	}

	sg.SetSlotBusyState(lesson.LessonSlot, true)
	// TODO: Sharing busy state between groups causes bug: student group has a window, but between lessons of connected groups
	// for _, g := range sg.connectedGroups {
	// 	g.SetSlotBusyState(lesson.LessonSlot, true)
	// }

	return err
}

func (sg *StudentGroup) RemoveLesson(lesson *Lesson) error {
	if lesson.StudentGroup != sg {
		return fmt.Errorf("invalid lesson")
	}

	err := sg.SetSlotBusyState(lesson.LessonSlot, false)
	if err != nil {
		return err
	}
	// TODO: Sharing busy state between groups causes bug: student group has a window, but between lessons of connected groups
	// for _, g := range sg.connectedGroups {
	// 	g.SetSlotBusyState(lesson.LessonSlot, true)
	// }

	return nil
}

// CheckLesson checks if the lesson can be added. It checks slot validation, availability,
// day load and possible formation of the gap.
//
// Return an error if validation fails.
func (sg *StudentGroup) CheckLesson(lesson *Lesson) error {
	if err := sg.CheckSlot(lesson.LessonSlot); err != nil {
		return err
	}
	if !sg.IsFree(lesson.LessonSlot) {
		return fmt.Errorf("student group is busy")
	}
	if sg.CheckDayOverload(lesson.Day) {
		return fmt.Errorf("student group is fully loaded for this day")
	}
	if err := sg.CheckGapOnAdd(lesson.LessonSlot); err != nil {
		return err
	}

	if !sg.IsDayOfType(lesson.Type, lesson.Day) {
		return fmt.Errorf("type %s not in the correct day", lesson.Type.Name)
	}

	return nil
}

func (sg *StudentGroup) GetOvertimeLessons() (days []int) {
	days = []int{}

	for day := 0; true; day++ {
		count := sg.CountLessonsOn(day)
		if count == -1 {
			break
		}
		if count > sg.MaxLessonsPerDay {
			days = append(days, day)
		}
	}

	return
}

type InvalidLessonByType struct {
	Lesson           *Lesson
	ActualLessonType *LessonType
}

func (sg *StudentGroup) GetInvalidLessonsByType() []InvalidLessonByType {
	res := []InvalidLessonByType{}
	lessons := sg.GetAssignedLessons()

	for _, lesson := range lessons {
		if !sg.IsDayOfType(lesson.Type, lesson.Day) {
			res = append(res, InvalidLessonByType{
				Lesson:           lesson,
				ActualLessonType: sg.GetTypeOfDay(lesson.Day),
			})
		}
	}

	return res
}

func (sg *StudentGroup) GetSlotDeficitOfReservedSlotsForLT() int {
	count := 0
	lessonTypes := sg.GetLessonTypes()

	for _, lt := range lessonTypes {
		delta := sg.GetReservedSlotsForLT(lt) - sg.GetSlotCountForLType(lt)
		if delta < 0 {
			count -= delta
		}
	}

	return count
}
