openapi: 3.1.0
info:
  title: API Gateway
  version: 0.0.1.20260310

paths:
  /seed:
    any:
      summary: seed databases of all services
      responses:
        "204":
          description: NO CONTENT
        "500":
          description: INTERNAL SERVER ERROR
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /employee/academic-ranks:
    get:
      tags:
        - employee-service
      summary: gets all academic ranks from database
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                      description: Unique identifier of the academic rank
                    slug:
                      type: string
                      description: Unique slug used internally
                    title:
                      type: string
                      description: Human-readable name of the rank
                    created_at:
                      type: string
                      format: date-time
                      description: Record creation timestamp
                    updated_at:
                      type: string
                      format: date-time
                      description: Record last update timestamp
